run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gosec
    - gofmt
    - goimports

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
